const WOMEN_IMAGES = [
  "women/IMG_7144/main.jpg",
  "women/IMG_7201/main.jpg",
  "women/IMG_7204/main.jpg",
  "women/IMG_7207/main.jpg",
];

const MEN_IMAGES = [
  "men/IMG_5125/main.jpg",
  "men/IMG_7265/main.jpg",
  "men/IMG_8310/main.jpg",
  "men/IMG_8319/main.jpg",
  "men/IMG_8477/main.jpg",
  "men/IMG_8653/main.jpg",
  "men/IMG_8658/main.jpg",
  "men/IMG_9158/main.jpg",
];

function productImage(category, index, offset = 0) {
  const pool = category === "women" ? WOMEN_IMAGES : MEN_IMAGES;
  return pool[(index + offset) % pool.length];
}

const YELLUJEAN_PRODUCTS = [
  {
    id: 1,
    name: "????? ? ??? ??",
    price: 890000,
    salePrice: null,
    category: "women",
    type: "outer",
    tags: ["new", "best"],
    image: productImage("women", 0),
    imageHover: productImage("women", 0, 1),
    badge: "NEW",
  },
  {
    id: 2,
    name: "???? ??? ???",
    price: 420000,
    salePrice: null,
    category: "women",
    type: "knit",
    tags: ["new"],
    image: productImage("women", 1),
    imageHover: productImage("women", 1, 1),
    badge: "NEW",
  },
  {
    id: 3,
    name: "??? ?? ????",
    price: 380000,
    salePrice: null,
    category: "women",
    type: "pants",
    tags: ["best"],
    image: productImage("women", 2),
    imageHover: productImage("women", 2, 1),
    badge: null,
  },
  {
    id: 4,
    name: "?? ?? ????",
    price: 520000,
    salePrice: null,
    category: "women",
    type: "top",
    tags: ["new"],
    image: productImage("women", 3),
    imageHover: productImage("women", 3, 1),
    badge: "NEW",
  },
  {
    id: 5,
    name: "?? ????? ? ??",
    price: 1290000,
    salePrice: 1032000,
    category: "women",
    type: "outer",
    tags: ["best", "sale"],
    image: productImage("women", 0, 2),
    imageHover: productImage("women", 0, 3),
    badge: "20%",
  },
  {
    id: 6,
    name: "??? ?? ??",
    price: 680000,
    salePrice: 544000,
    category: "women",
    type: "outer",
    tags: ["sale"],
    image: productImage("women", 1, 2),
    imageHover: productImage("women", 1, 3),
    badge: "20%",
  },
  {
    id: 7,
    name: "???? ? ????",
    price: 980000,
    salePrice: null,
    category: "men",
    type: "outer",
    tags: ["new", "best"],
    image: productImage("men", 0),
    imageHover: productImage("men", 0, 1),
    badge: "NEW",
  },
  {
    id: 8,
    name: "????? ???? ??",
    price: 390000,
    salePrice: null,
    category: "men",
    type: "top",
    tags: ["new"],
    image: productImage("men", 1),
    imageHover: productImage("men", 1, 1),
    badge: "NEW",
  },
  {
    id: 9,
    name: "???? ? ??",
    price: 420000,
    salePrice: null,
    category: "men",
    type: "pants",
    tags: ["best"],
    image: productImage("men", 2),
    imageHover: productImage("men", 2, 1),
    badge: null,
  },
  {
    id: 10,
    name: "??? ? ??",
    price: 1890000,
    salePrice: 1512000,
    category: "men",
    type: "outer",
    tags: ["sale", "best"],
    image: productImage("men", 3),
    imageHover: productImage("men", 3, 1),
    badge: "20%",
  },
  {
    id: 11,
    name: "?? ?? · ??",
    price: 980000,
    salePrice: null,
    category: "acc",
    type: "shoes",
    tags: ["best", "new"],
    image: "https://images.unsplash.com/photo-1572804013309-59a23b123e5f?w=600&q=80",
    imageHover: "https://images.unsplash.com/photo-1549298916-b41d501c3775?w=600&q=80",
    badge: "NEW",
  },
  {
    id: 12,
    name: "?????? ?? ?",
    price: 1450000,
    salePrice: null,
    category: "acc",
    type: "bag",
    tags: ["new"],
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d1282d?w=600&q=80",
    imageHover: "https://images.unsplash.com/photo-1590874103328-eac46a683ceb?w=600&q=80",
    badge: "NEW",
  },
  {
    id: 13,
    name: "?? ?? ???",
    price: 280000,
    salePrice: 224000,
    category: "acc",
    type: "jewelry",
    tags: ["sale"],
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
    imageHover: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80",
    badge: "20%",
  },
  {
    id: 14,
    name: "? ?? · ??",
    price: 180000,
    salePrice: 144000,
    category: "acc",
    type: "hat",
    tags: ["sale"],
    image: "https://images.unsplash.com/photo-1576871337639-b9aef838c17a?w=600&q=80",
    imageHover: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&q=80",
    badge: "20%",
  },
  {
    id: 15,
    name: "??? ? ???",
    price: 480000,
    salePrice: null,
    category: "women",
    type: "knit",
    tags: ["new"],
    image: productImage("women", 2, 2),
    imageHover: productImage("women", 2, 3),
    badge: "NEW",
  },
  {
    id: 16,
    name: "?????? ? ???",
    price: 560000,
    salePrice: 448000,
    category: "women",
    type: "pants",
    tags: ["sale"],
    image: productImage("women", 3, 2),
    imageHover: productImage("women", 3, 3),
    badge: "20%",
  },
  {
    id: 17,
    name: "?? ??? ???",
    price: 190000,
    salePrice: null,
    category: "men",
    type: "top",
    tags: ["new"],
    image: productImage("men", 4),
    imageHover: productImage("men", 4, 1),
    badge: "NEW",
  },
  {
    id: 18,
    name: "??? ? ?? ???",
    price: 890000,
    salePrice: 712000,
    category: "acc",
    type: "shoes",
    tags: ["sale", "best"],
    image: "https://images.unsplash.com/photo-1549298916-b41d501c3775?w=600&q=80",
    imageHover: "https://images.unsplash.com/photo-1572804013309-59a23b123e5f?w=600&q=80",
    badge: "20%",
  },
];

const PRODUCT_TYPE_LABELS = {
  outer: "???",
  top: "??",
  knit: "??",
  pants: "??",
  shoes: "??",
  bag: "?",
  jewelry: "???",
  hat: "??",
};

const YELLUJEAN_EDITORIALS = [
  {
    id: 1,
    title: "Form & Function ? ?? ??? ??",
    excerpt: "????? ??? ???? ???",
    date: "2026-05-20",
    category: "essay",
    image: "assets/home/IMG_7232.jpg",
    featured: true,
  },
  {
    id: 2,
    title: "Layering Guide",
    excerpt: "??? ???? ??? ???",
    date: "2026-05-15",
    category: "guide",
    image: "assets/home/IMG_7244.jpg",
    featured: false,
  },
  {
    id: 3,
    title: "Studio Visit: Seoul",
    excerpt: "yellujean ????? ?? ??? ???",
    date: "2026-05-08",
    category: "interview",
    image: "assets/home/IMG_6756.jpg",
    featured: false,
  },
  {
    id: 4,
    title: "The Coat Edit",
    excerpt: "?? ?? ? ?? ? ??? 6",
    date: "2026-05-01",
    category: "edit",
    image: "assets/home/IMG_8310.jpg",
    featured: false,
  },
  {
    id: 5,
    title: "Neutral Palette",
    excerpt: "??? ??? ???? ??? ?",
    date: "2026-04-22",
    category: "lookbook",
    image: "assets/home/IMG_8319.jpg",
    featured: false,
  },
  {
    id: 6,
    title: "Making of 26 S/S",
    excerpt: "???? ????, ?? ??? ?? ??",
    date: "2026-04-10",
    category: "interview",
    image: "assets/home/IMG_2906.jpg",
    featured: false,
  },
];

const PAGE_CONFIG = {
  new: {
    title: "NEW",
    subtitle: "?? ? ??",
    description: "26 S/S ??, yellujean? ??? ??.",
    filter: (p) => p.tags.includes("new"),
    types: ["all", "outer", "top", "knit", "pants"],
  },
  women: {
    title: "WOMEN",
    subtitle: "?? ???",
    description: "yellujean ?? ?? ? ??? ???? ?????.",
    filter: (p) => p.category === "women",
    types: ["all", "outer", "top", "knit", "pants"],
  },
  men: {
    title: "MEN",
    subtitle: "?? ???",
    description: "yellujean ?? ?? ? ????? ??? ???.",
    filter: (p) => p.category === "men",
    types: ["all", "outer", "top", "knit", "pants"],
  },
  acc: {
    title: "ACC",
    subtitle: "????",
    description: "yellujean ???? ? ???? ???? ?.",
    filter: (p) => p.category === "acc",
    types: ["all", "shoes", "bag", "jewelry", "hat"],
  },
  sale: {
    title: "SALE",
    subtitle: "?? ??",
    description: "yellujean ?? ?? ? ?? 20% OFF.",
    filter: (p) => p.tags.includes("sale") || p.salePrice,
    types: ["all", "outer", "top", "knit", "pants", "shoes", "bag"],
  },
};

function formatPrice(n) {
  return "?" + n.toLocaleString("ko-KR");
}

function resolveProductAsset(path) {
  if (!path || path.startsWith("http")) return path;
  const inPages = /\/pages\//.test(window.location.pathname);
  return (inPages ? "../" : "") + "assets/products/" + path;
}

function resolveSiteAsset(path) {
  if (!path || path.startsWith("http")) return path;
  const inPages = /\/pages\//.test(window.location.pathname);
  if (path.startsWith("assets/")) {
    return (inPages ? "../" : "") + path;
  }
  return path;
}
